name: Render Deployment

on:
  push:
    branches:
      - next
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_PWD }}
      DATABASE_URL: ${{ secrets.PROD_DB }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Get Store Path
        id: get-store-path
        run: echo "store-path=$(pnpm store path)\n" >> $GITHUB_OUTPUT
      - name: Setup Cache
        id: setup-cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/*lock*', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/*lock*', 'package.json') }}
            ${{ runner.os }}-
          path: |
            node_modules
            ${{ steps.get-store-path.outputs.store-path }}
            .netlify
      - name: Install Dependencies 📦
        if: steps.setup-cache.outputs.cache-hit != 'true'
        run: pnpm i
      - name: Migrate Database Schema
        run: pnpm migrate.prod
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          push: true,
          tags: brinestone/tellthem-api:${{ github.ref_name }}
