name: Render Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - next
      - f/*
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_PWD }}
      DATABASE_URL: ${{ secrets.PROD_DB }}
      SYSTEM_WALLET: ${{ secrets.SYSTEM_WALLET }}
      SYSTEM_STARTING_BALANCE: ${{ vars.SYSTEM_STARTING_BALANCE }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Get Store Path
        id: get-store-path
        run: echo "store-path=$(pnpm store path)\n" >> $GITHUB_OUTPUT
      - name: Setup Cache
        id: setup-cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/*lock*', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/*lock*', 'package.json') }}
            ${{ runner.os }}-
          path: |
            node_modules
            ${{ steps.get-store-path.outputs.store-path }}
            .netlify
      - name: Install Dependencies 📦
        if: steps.setup-cache.outputs.cache-hit != 'true'
        run: pnpm i
      - name: Migrate Database Schema
        run: pnpm migrate.prod
      - name: Seed Database
        run: pnpm db.seed
      - name: Build ⚙️
        run: pnpm build
      - name: Build Docker Image ⚙️
        id: docker-build
        run: |
          docker build . -t ${{ env.DOCKER_USERNAME }}/tellthem-api:$(echo "${{github.ref_name}}" | cut -d "/" -d "v" -f 2)
          echo "image-name=\"${{ env.DOCKER_USERNAME }}/tellthem-api:$(echo "${{github.ref_name}}" | cut -d "/" -d "v" -f 2)\"\n" >> $GITHUB_OUTPUT
      - name: Docker Push ⬆️
        run: |
          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_TOKEN }}
          docker push ${{ steps.docker-build.outputs.image-name }}
